### ISSUE TITLE
Minecraft Crash Report 1.20.1

### ISSUE THREAD

**Issue by SkrimanS** [RobertSkalko/Mine-And-Slash-Rework#12]
I encountered this problem.
This happens at night in the overworld and in the nether

---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-09-30 12:35:07
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_9236_()" because "p" is null
	at com.robertx22.age_of_exile.database.data.profession.ProfessionEvents.lambda$init$1(ProfessionEvents.java:61) ~[Mine_and_Slash_BETA-1.20.1-5.1.2.jar%23322!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.world.entity.animal.Animal.m_27563_(Animal.java:210) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.ai.goal.BreedGoal.m_8026_(BreedGoal.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.BreedGoal.m_8037_(BreedGoal.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:120) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:111) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:760) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mmorpg-mixins.json:StopMapMobDropsMixin,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2547) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:StopMobDropWornGearInMapsMixin,pl:mixin:APP:mixins.enderio.json:LivingEntityMixin,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mmorpg-mixins.json:StopMapMobDropsMixin,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:128) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.animal.Chicken.m_8107_(Chicken.java:85) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2297) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:StopMobDropWornGearInMapsMixin,pl:mixin:APP:mixins.enderio.json:LivingEntityMixin,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mmorpg-mixins.json:StopMapMobDropsMixin,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.robertx22.age_of_exile.database.data.profession.ProfessionEvents.lambda$init$1(ProfessionEvents.java:61) ~[Mine_and_Slash_BETA-1.20.1-5.1.2.jar%23322!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.world.entity.animal.Animal.m_27563_(Animal.java:210) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.ai.goal.BreedGoal.m_8026_(BreedGoal.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.BreedGoal.m_8037_(BreedGoal.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:120) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:111) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:760) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mmorpg-mixins.json:StopMapMobDropsMixin,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2547) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:StopMobDropWornGearInMapsMixin,pl:mixin:APP:mixins.enderio.json:LivingEntityMixin,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mmorpg-mixins.json:StopMapMobDropsMixin,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:128) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.animal.Chicken.m_8107_(Chicken.java:85) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2297) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:mmorpg-mixins.json:StopMobDropWornGearInMapsMixin,pl:mixin:APP:mixins.enderio.json:LivingEntityMixin,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mmorpg-mixins.json:StopMapMobDropsMixin,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:chicken (net.minecraft.world.entity.animal.Chicken)
	Entity ID: 45518
	Entity Name: Курица
	Entity's Exact location: 789.32, 64.00, -128.20
	Entity's Block location: World: (789,64,-129), Section: (at 5,0,15 in 49,4,-9; chunk contains blocks 784,-64,-144 to 799,319,-129), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Age:0,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.0d,Name:"forge:step_height_addition"},{Base:0.25d,Name:"minecraft:generic.movement_speed"},{Base:4.0d,Name:"minecraft:generic.max_health"}],BalmData:{},Brain:{memories:{}},CanPickUpLoot:0b,CanUpdate:1b,DeathTime:0s,EggLayTime:7226,FallDistance:0.0f,FallFlying:0b,Fire:-1s,ForcedAge:0,ForgeCaps:{"curios:inventory":{Curios:[]},"library_of_exile:entity_info":{OTHER:"spawn",dmg_stats:'{"map":{},"enviroOrMobDmg":0.0}',spawn_pos:0L},"mmorpg:entity_data":{ENTITY_TYPE:"ANIMAL",affix:'{"affixes":["nature_lord"]}',ailments:'{"dotMap":{},"strMap":{},"dmgMap":{},"lastAttacker":""}',cds:'{"map":{}}',custom_stats:'{"stats":{},"mods":{}}',do_sync:1b,eq_changed:1b,ex_d:0,exp:0,hp:43,is_a_newbie:1b,leech:'{"map":{}}',level:12,"mmorpg:custom_exact_stats_data":'{"stats":{},"mods":{}}',pet:'{"spell":"","ticks":0}',rarity:"rare",res_loc:'{"mana":0.0,"magic_shield":0.0,"energy":0.0,"blood":0.0}',set_mob_stats:1b,statuses:'{"exileMap":{}}',th:'{"map":{}}',unit_object:'{"stats":{"stats":{"health_regen":{"id":"health_regen","v1":1.6,"m":1.0},"dodge":{"id":"dodge","v1":0.0,"m":1.0},"critical_hit":{"id":"critical_hit","v1":9.75,"m":1.0},"chaos_weapon_damage":{"id":"chaos_weapon_damage","v1":3.2,"m":1.0},"health":{"id":"health","v1":43.84,"m":1.0},"accuracy":{"id":"accuracy","v1":3.2,"m":1.0},"extra_mob_drops":{"id":"extra_mob_drops","v1":20.0,"m":1.0},"total_damage":{"id":"total_damage","v1":0.0,"m":1.0},"poison_chance":{"id":"poison_chance","v1":5.0,"m":1.0},"armor":{"id":"armor","v1":64.0,"m":1.0},"water_resist":{"id":"water_resist","v1":40.0,"m":1.0},"elemental_resist":{"id":"elemental_resist","v1":0.0,"m":1.0},"spell_damage":{"id":"spell_damage","v1":-25.0,"m":1.0},"phys_to_chaos":{"id":"phys_to_chaos","v1":75.0,"m":1.0},"fire_resist":{"id":"fire_resist","v1":40.0,"m":1.0},"lightning_resist":{"id":"lightning_resist","v1":40.0,"m":1.0}}}}',uuid:""}},ForgeData:{},HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:4.0f,HurtByTimestamp:0,HurtTime:0s,InLove:0,Invulnerable:0b,IsChickenJockey:0b,LeftHanded:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PersistenceRequired:0b,PortalCooldown:0,Pos:[789.3221999069625d,64.0d,-128.20000000298023d],Rotation:[184.57611f,0.0f],UUID:[I;767347146,-534296575,-1513916990,-1597598192]}
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Skriman'/45502, l='ServerLevel[Start]', x=789.47, y=63.00, z=-134.02]]
	Chunk stats: 3890
	Level dimension: minecraft:overworld
	Level spawn location: World: (7,100,86), Section: (at 7,4,6 in 0,6,5; chunk contains blocks 0,-64,80 to 15,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2632822 game time, 1109 day time
	Level name: Start
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 128164 (now: false), thunder time: 4470 (now: true)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by RobertSkalko** [comment]
I see the problem, so the breed event can be caused by a non player, will be fixed
